FROM arm32v7/debian:buster

RUN apt-get update && apt-get install -yq \
	network-manager && \
	apt-get clean && rm -rf /var/lib/apt/lists/* && \
	systemctl mask NetworkManager.service

WORKDIR /usr/src/app

COPY . .

CMD ./nmcli
